### ISSUE TITLE
I put the JBoss5XmlWebApplicationContext  but keep getting 'Could not detect JBoss VFS infrastructure'

### ISSUE THREAD

**Issue by vhorvath001** [arey/spring4-vfs2-support#2]
Hi,

First of all thanks for the patch!
I added the following to the web.xml

```
    <context-param>
       <param-name>contextClass</param-name>
       <param-value>com.javaetmoi.core.spring.JBoss5XmlWebApplicationContext</param-value>
    </context-param>
```

but keep getting the 

    [exec] Caused by: java.lang.IllegalStateException: Could not detect JBoss VFS infrastructure
    [exec] 	at org.springframework.core.io.VfsUtils.<clinit>(VfsUtils.java:94)

when trying to deploy my application.

This is the full relating part from the web.xml:
```
   <listener>
      <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
   </listener>
   <context-param>
      <param-name>contextClass</param-name>
      <param-value>com.javaetmoi.core.spring.JBoss5XmlWebApplicationContext</param-value>
   </context-param>
   <context-param>
      <param-name>contextConfigLocation</param-name>
      <param-value>/WEB-INF/applicationContext.xml,
                      classpath:quartzContext.xml</param-value>
   </context-param>
```

All I did was to add the dependency to maven and add the context-param. 
Do I have to do anything else?
Any hint would be appreciated!

Thanks,
V.

**Comment by vhorvath001** [comment]
Good morning,

Any hint please ?

Thanks,
V.

**Comment by arey** [comment]
Hi, in your stacktrace, the provided Vfs2Utils is not used. Is should be. Did you have the full stackstrace and the full web.xml?

**Comment by vhorvath001** [comment]
Hi,
Thanks for getting back to me!
It turned out that there was nothing wrong with the spring4-vfs2-support library but we use a beast called DWR (...) and this one messes things up.
Anyway it just works fine, thanks for this solution!
Thanks, V.
